##tomcat配置
server:
    port: 8088
    servlet:
        path: /
    tomcat:
        uri-encoding: UTF-8
##mybatis-plus配置
mybatis-plus:
    mapper-locations: classpath:/mapper/*Mapper.xml
    type-aliases-package: com.springboot.demo.entity
##日志配置
logback:
  logdir: logs/
  appname: springboot-test
logging:
  config: classpath:logback-spring.xml
##devtools热部署配置
spring:
  devtools:
    remote:
      restart:
        enabled: true
    restart:
      enabled: true
      additional-paths: src/main/java
  datasource:
    url: jdbc:mysql://localhost:8066/tenant1?useUnicode=true&characterEncoding=UTF-8
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: chenjingxue
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      minimum-idle: 5
      maximum-pool-size: 15
      auto-commit: true
      idle-timeout: 30000
      pool-name: myHikariPool
      max-lifetime: 1800000
      connection-timeout: 30000
      connection-test-query: select 1

